# Generated by Django 5.1 on 2024-08-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_idea_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
