# Generated by Django 5.1 on 2024-08-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_idea_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='img',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
